[package]
name = "du-rs"
version = "0.1.0"
authors = ["oyundev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustop = "*"
may = "*"
